#!/usr/bin/env sh
#
# Run all dotfiles installers.

set -e

cd $DOTHOME

# find the installers and run them iteratively
find . -name install.sh | while read installer; do echo "> ${installer}" && sh -c "${installer}" && echo ""; done
