#!/usr/bin/env sh
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    loginfo '> setup gitconfig'

    git_credential='cache'

    loguser ' - What is your github author name?'
    read -e git_authorname
    loguser ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.example > git/gitconfig.local.symlink

    logsuccess 'gitconfig'
  fi
}

install_dotfiles () {
  loginfo '> installing dotfiles'

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_XDG_dotfiles () {
  loginfo '> installing dotfiles for XDG_CONFIG_HOME'

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.xdg' -not -path '*.git*')
  do
    dir=$(dirname $src)
    app=${dir##*/}
    dst="$HOME/.config/$app/$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

setup_gitconfig

install_dotfiles

install_XDG_dotfiles

logsuccess 'Finished!'
