#!/usr/bin/env sh
#
# move snap .desktop files.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

symlink_snap_apps() {
    if [ -d git/gitconfig.local.symlink ]; then
        loginfo '> symlinking snaps'

        local source="/var/lib/snapd/desktop/applications"
        local target="$HOME/.local/share/applications"

        for src in $(find -H "$source" -name '*.desktop'); do
            filename=${src##*/}
            dst="$target/$filename"
            link_file "$src" "$dst" | loginfo
        done
    else 
        loginfo 'no snaps to be symlinked'
    fi

}

symlink_snap_apps
logsuccess 'Done with symlinking snaps!'
