#!/usr/bin/env sh
#
# move snap .desktop files.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

symlink_snaps() {
    loginfo '> symlinking snaps'

    local source="/var/lib/snapd/desktop/applications"
    local target="$HOME/.local/share/applications"

    for src in $(find -H "$source" -name '*.desktop'); do
        filename=${src##*/}
        dst="$target/$filename"
        link_file "$src" "$dst"
    done
}

symlink_snaps
logsuccess 'Done with symlinking snaps!'
